### PR TITLE
fix: find local settings when working file dir is not working dir

### LINKED ISSUE #421: Local settings with -l switch only found if called `localSettings.yaml` when called from different directory
The documentation explains there are four possible names for local settings, `localSettings.yaml`, `latexindent.yaml`, `.localSettings.yaml`, and `.latexindent.yaml`, which the program first searches (when called with the -l switch without providing the explicit settings file) in the same directory of the working file and the in the current working directory; see 

https://github.com/cmhughes/latexindent.pl/blob/f2b7b05b8c1606b1445aafae411e5238aee621ed/documentation/sec-indent-config-and-settings.rst#L61-L83

However, if `latexindent` is called from another directory than the working file, the detection only works if the local settings name is `localSettings.yaml`. I believe this is because of the following (incomplete) if statement that should consider all four options:

https://github.com/cmhughes/latexindent.pl/blob/f2b7b05b8c1606b1445aafae411e5238aee621ed/LatexIndent/GetYamlSettings.pm#L331-L342

The following MWE is only for the demonstration; please see the included logs that the local settings are only found if `latexindent` is called from the files directory. For clarification, I assume the provided snippets are save as:

```bash
tex/
|- mwe.tex
| .latexindent.yaml
```

original .tex code
--
```tex
% tex/mwe.tex

\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\begin{document}

\begin{equation}
z
={\left(
x+
y
\right)}^2
\end{equation}

\end{document}
```

yaml settings
--

```yaml
# tex/.localsettings.yaml
defaultIndent: "\t\t"
```

*Please paste the output you receive here*
--

```bash
latexindent -l tex/mwe.tex
```

```tex
\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\begin{document}

\begin{equation}
	z
	={\left(
	x+
	y
	\right)}^2
\end{equation}

\end{document}
```

```log
INFO:  latexindent version 3.20.2, 2023-02-04, a script to indent .tex files
       latexindent lives here: /usr/local/texlive/2022/texmf-dist/scripts/latexindent/
       Tue Feb 14 15:05:38 2023
       Filename: tex/mwe.tex
INFO:  Processing switches:
INFO:  Directory for backup files and indent.log:
       tex
INFO:  YAML settings read: defaultSettings.yaml
       Reading defaultSettings.yaml from /usr/local/texlive/2022/texmf-dist/scripts/latexindent/defaultSettings.yaml
INFO:  YAML reading settings
       Home directory is /Users/******
       latexindent.pl didn't find indentconfig.yaml or .indentconfig.yaml
       see all possible locations: https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html#indentconfig-options)
INFO:  -l switch used without filename, will search for the following files in turn:
       localSettings.yaml,latexindent.yaml,.localSettings.yaml,.latexindent.yaml
INFO:  YAML settings read: -l switch
       Multiple localSettings found, separated by commas:
       localSettings.yaml, latexindent.yaml, .localSettings.yaml, .latexindent.yaml
WARN:  yaml file not found: localSettings.yaml not found. Proceeding without it.
WARN:  yaml file not found: latexindent.yaml not found. Proceeding without it.
WARN:  yaml file not found: .localSettings.yaml not found. Proceeding without it.
WARN:  yaml file not found: .latexindent.yaml not found. Proceeding without it.
INFO:  Phase 1: searching for objects
INFO:  Phase 2: finding surrounding indentation
INFO:  Phase 3: indenting objects
INFO:  Phase 4: final indentation check
INFO:  Output routine:
       Not outputting to file; see -w and -o switches for more options.
       --------------
INFO:  Please direct all communication/issues to:
        https://github.com/cmhughes/latexindent.pl

```

desired or expected output
--
```bash
(cd tex && latexindent -l mwe.tex)
```

```tex
\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\begin{document}

\begin{equation}
		z
		={\left(
		x+
		y
		\right)}^2
\end{equation}

\end{document}
```

```log
INFO:  latexindent version 3.20.2, 2023-02-04, a script to indent .tex files
       latexindent lives here: /usr/local/texlive/2022/texmf-dist/scripts/latexindent/
       Tue Feb 14 15:06:34 2023
       Filename: mwe.tex
INFO:  Processing switches:
INFO:  Directory for backup files and indent.log:
       .
INFO:  YAML settings read: defaultSettings.yaml
       Reading defaultSettings.yaml from /usr/local/texlive/2022/texmf-dist/scripts/latexindent/defaultSettings.yaml
INFO:  YAML reading settings
       Home directory is /Users/******
       latexindent.pl didn't find indentconfig.yaml or .indentconfig.yaml
       see all possible locations: https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html#indentconfig-options)
INFO:  -l switch used without filename, will search for the following files in turn:
       localSettings.yaml,latexindent.yaml,.localSettings.yaml,.latexindent.yaml
INFO:  YAML settings read: -l switch
       Multiple localSettings found, separated by commas:
       localSettings.yaml, latexindent.yaml, .localSettings.yaml, .latexindent.yaml
       Adding .latexindent.yaml to YAML read paths
INFO:  YAML settings, reading from the following files:
       Reading USER settings from .latexindent.yaml
       ---
       defaultIndent: "\t\t"

INFO:  Phase 1: searching for objects
INFO:  Phase 2: finding surrounding indentation
INFO:  Phase 3: indenting objects
INFO:  Phase 4: final indentation check
INFO:  Output routine:
       Not outputting to file; see -w and -o switches for more options.
       --------------
INFO:  Please direct all communication/issues to:
        https://github.com/cmhughes/latexindent.pl
```

### PR DESCRIPTION
**Pull request by hsloot**
When latexindent is called with the `-l` switch on a file that is not in the current working directory, local settings in the same directory as this file are only found if it has the name `localSettings.yaml`; for the other four documented options `latexindent.yaml`, `.localSettings.yaml`, and `.latexindex.yaml`, the local settings files are not found or used (see #421).

The issue should be fixed by replacing the condition `$_ eq "localSettings.yaml"` by `$_ =~ /^[.]?(localSettings|latexindent)\.yaml$/` in the following part 

https://github.com/cmhughes/latexindent.pl/blob/f2b7b05b8c1606b1445aafae411e5238aee621ed/LatexIndent/GetYamlSettings.pm#L331-L342

does this relate to an existing issue?
-
Fix #421

does this change any existing behavior?
-
*yes/no*

what does this add?
-
See above.

how do I test this?
-
The behavior is documented with four tests in `test-cases/batch-tests`  that run latexindent on four subdirectories `test-cases/batch-tests/local-settings-friend-*`; each folder contains a local settings file with names `localSettings.yaml`, `latexindent.yaml`, `.localSettings.yaml`, and `.latexindent.yaml` and a small LaTeX file. The local settings only change `defaultIndent: "\t\t"`. The four tests run latexindent on the  LaTeX file, grep "defaultIndent", trim left spaces, and write the result to the local settings file; if everything works, the file should remain unchanged.

### CODE REVIEW

**Comment by hsloot** [comment]
As suggested, a PR trying to fix #421. Disclaimer: My Perl knowledge is limited, and I have no setup for developing with Perl; however, if I am right and the fix is as simple as I think, the GH action tests should tell if is works. What I have done:

- Verified with my texlive version of latexindent that the test added in [c5881ef](https://github.com/cmhughes/latexindent.pl/pull/422/commits/c5881efe7c33df5db943fb1905a26a209b72b2de) is successful and that the tests added in [408e589](https://github.com/cmhughes/latexindent.pl/pull/422/commits/408e589b5032cd6a1351a6de05155c488740cfa9) fail (which is the documented behavior in #421).
- Verified with an online Perl compiler that the added regular expression is valid and matches all four "friend"-file names of `localSettings.yaml`.

**Comment by hsloot** [comment]
I also added a test with a local settings file with a slightly different name, `localSetting.yaml`; in this case, the test should fail if it is read anyway with just the `-l` switch.

**Comment by cmhughes** [comment]
Thanks for this!

I'll get to reviewing it soon. I'm sorry that development is slow at the moment.

File: test-cases/batch-tests/batch-tests.sh [hunk 1]
```diff
@@ -28,5 +28,26 @@ latexindent.pl -s cmh.tex lines*.tex -g fatal-file-not-exist.log
 latexindent.pl -s cmh1.tex lines*.tex -g fatal-file-no-read.log
 
 latexindent.pl -l documentation.yaml -rv -w -m -s -g not-working.log doc*.tex
+
+# local settings found with default name (friend #1)
+latexindent.pl -s -l local-settings-friend-1/mwe.tex
+(cd local-settings-friend-1 && (cat indent.log | grep "defaultIndent" | sed 's/^ *//g' > localSettings.yaml))
```
Comment (cmhughes) [inline test-cases/batch-tests/batch-tests.sh:34]: I don't think we need this line. Similarly for the analogous ones below.

Comment (cmhughes) [reply test-cases/batch-tests/batch-tests.sh:34]: It's line 34 that isn't needed. Line 33 looks fine.

Comment (hsloot) [reply test-cases/batch-tests/batch-tests.sh:34]: Are you sure? If I understand the test concept correctly, a test fails if something tracked by git is changed, right? Line 33 will run successfully no matter if the local settings file is found or not; the command also does not modify the file or writes out the result into another file, so line 34 is required to modify the settings if they are not read correctly ("\t\t" gets replaced by "\t" if the local settings are not considered) ... so I think it is required. However, there are at least two alternatives:

1. Use the flag `-o=+out` and provide corresponding files with the desired output. 

2. Only grep the lines matching "WARN" and provide a corresponding file with the expected warnings (as I have done for the last test (lines 48-50).

I am happy to change something or remove tests if you want; they are on separate commits and could be reverted. However, I like the second alternative the most as it's more obvious what is tested.

Comment (cmhughes) [reply test-cases/batch-tests/batch-tests.sh:34]: Yes, you've understood the test cases :) I like your option 2,that makes sense. Feel free to keep adding commits, they will ultimately be squashed into 1 when merged

File: test-cases/batch-tests/batch-tests.sh [hunk 2]
```diff
@@ -31,19 +31,19 @@ latexindent.pl -l documentation.yaml -rv -w -m -s -g not-working.log doc*.tex
 
 # local settings found with default name (friend #1)
 latexindent.pl -s -l local-settings-friend-1/mwe.tex
-(cd local-settings-friend-1 && (cat indent.log | grep "defaultIndent" | sed 's/^ *//g' > localSettings.yaml))
+(cd local-settings-friend-1 && (cat indent.log | grep "WARN" > warnings.txt))
```
Comment (cmhughes) [inline test-cases/batch-tests/batch-tests.sh:34]: Great, thanks! Is it possible to do this without changing directory?

Comment (hsloot) [reply test-cases/batch-tests/batch-tests.sh:34]: yes, but it is a shortcut for not having to type the directory twice; the longer (equivalent) of this particular line would read:

```diff
- (cd local-settings-friend-1 && (cat indent.log | grep "WARN" > warnings.txt))
+ cat local-settings-friend-1/indent.log | grep "WARN" > local-settings-friend-1/warnings.txt
```

as the command inside parenthesis `( ... )` is run in a subshell, the directory is never directly changed in this shell itself; if you want me to change it anyway, let me know.

**Comment by cmhughes** [comment]
I think I'd prefer the longer version, please, it's more obvious what's
going on at a glance.

**Comment by cmhughes** [comment]
Many thanks, this is great.
